apiRules:
- exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute
- exclude:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never
