name: 'Build Documentation'

on:
  push:
    branches:
      - master
      - release/*
      # temporarily while setting up documentation
      - documentation*

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Install docfx
      run: choco install docfx --version 2.50 -y

    - name: Checkout current commit
      uses: actions/checkout@v2

    - name: Checkout git-hub pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: output/docs

    - name: Test
      run: |
        echo "PWD = $PWD"
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "content of GITHUB_WORKSPACE root"
        ls "$GITHUB_WORKSPACE"
        echo "content of GITHUB_WORKSPACE/output/docs root"
        ls "$GITHUB_WORKSPACE/output/docs"

    # - name: Setup MSBuild.exe
    #   uses: warrenbuckley/Setup-MSBuild@v1

    # - name: Build and Package with MSBuild
    #   working-directory: src
    #   run: msbuild -t:"Clean;Build" -restore -p:Configuration=Release -p:TargetFramework=net471 LpSolveDotNet.sln
