name: 'Build Documentation'

on:
  push:
    branches:
      - master
      - release/*
      # temporarily while setting up documentation
      - documentation*

jobs:
  build_doc:
    if: github.repository == 'MarcelGosselin/LpSolveDotNet'

    runs-on: windows-latest

    env:
      ghpages_root_relative: output/docs
      ghpages_root: ${{github.workspace}}/output/docs
      ghpages_branch: gh-pages
      remote_repo: https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git
      commit_message: "Updated from GitHub workflow '${{github.workflow}}' #${{github.run_number}}"

    steps:

    # - name: Install docfx
    #   run: choco install docfx --version 2.50 -y

    # - name: Checkout current commit
    #   uses: actions/checkout@v2

    - name: Checkout git-hub pages
      uses: actions/checkout@v2
      with:
        ref: ${{env.ghpages_branch}}
        path: ${{env.ghpages_root_relative}}

    - name: Add dummy content to doc
      run: echo "This is from GitHub action" >> ${{env.ghpages_root}}/dummy.md

    # - name: Add files for git-hub pages commit 
    #   working-directory: ${{env.ghpages_root}}
    #   run: git add .

    # - name: Commit git-hub pages
    #   working-directory: ${{env.ghpages_root}}
    #   run: git commit -m "${{env.commit_message}}"
    - name: Prepare commit
      working-directory: ${{env.ghpages_root}}
      run: |
        git add .
        git diff --quiet --exit-code --staged
        echo "::set-env name={has_changes_to_commit}::{$LastExitCode}"

    - name: Commit files for git-hub pages commit
      if: env.has_changes_to_commit==1
      working-directory: ${{env.ghpages_root}}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "${{env.commit_message}}"

    - name: Push git-hub pages
      if: ${{env.has_changes_to_commit}}==1
      working-directory: ${{env.ghpages_root}}
      run: git push "${{env.remote_repo}}" HEAD:${{env.ghpages_branch}}

    # - name: Push git-hub pages
    #   uses: ad-m/github-push-action@0.5.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     directory: ${{env.ghpages_root}}
    #     branch: gh-pages

    # - name: Checkin git-hub pages
    #   uses: zwaldowski/git-commit-action@v1
    #   with:
    #     ref: gh-pages
    #     path: output/docs

    # - name: Setup MSBuild.exe
    #   uses: warrenbuckley/Setup-MSBuild@v1

    # - name: Build and Package with MSBuild
    #   working-directory: src
    #   run: msbuild -t:"Clean;Build" -restore -p:Configuration=Release -p:TargetFramework=net471 LpSolveDotNet.sln
